apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : emir-pod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: emir-namespace
  source:
    path   : "HelmCharts/MyChart2"
    repoURL: "git@github.com:Emir507/argocd.git"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values_dev.yaml
      parameters:
      - name: "container.image"
        value: temson13/temson13

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true   
